### ISSUE TITLE
split

### ISSUE THREAD

**Issue by NeilFraser** [JC-Orozco/BlocksIDE#1]
The regular expression is quoted here:

`foo.split(/\d/);`

This fails to render anything.

`'a1b2c'.split(/\d/);`

**Comment by JC-Orozco** [comment]
On version 0.3.4 the first example is solved but the second one not yet:
The regular expression in the example is no longer quoted.
String dot chaining is not yet supported.

**Comment by JC-Orozco** [comment]
Fixed on version 0.3.9
