### ISSUE TITLE
Map keys not converted to blocks correctly

### ISSUE THREAD

**Issue by RoboErikG** [JC-Orozco/BlocksIDE#2]
Creating a map with quoted elements like the following

var i={
  'foo': 'baz'
}

generates the attached blocks.
![image](https://cloud.githubusercontent.com/assets/11066279/26792477/66e87b1a-49cf-11e7-9e66-31a9a10cdc39.png)

**Comment by JC-Orozco** [comment]
Fixed on version 0.3.6
